/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca;


/**
 *
 * @author Aluno TDS
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        loja = new javax.swing.JMenu();
        livros = new javax.swing.JMenuItem();
        registrar = new javax.swing.JMenu();
        registrarlivro = new javax.swing.JMenuItem();
        registrarautor = new javax.swing.JMenuItem();
        registrarcliente = new javax.swing.JMenuItem();
        historico = new javax.swing.JMenu();
        listaautores = new javax.swing.JMenuItem();
        listaclientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");

        loja.setText("store");

        livros.setText("books");
        livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosActionPerformed(evt);
            }
        });
        loja.add(livros);

        jMenuBar1.add(loja);

        registrar.setText("register");

        registrarlivro.setText("register book");
        registrarlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarlivroActionPerformed(evt);
            }
        });
        registrar.add(registrarlivro);

        registrarautor.setText("register actor");
        registrarautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarautorActionPerformed(evt);
            }
        });
        registrar.add(registrarautor);

        registrarcliente.setText("register client");
        registrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarclienteActionPerformed(evt);
            }
        });
        registrar.add(registrarcliente);

        jMenuBar1.add(registrar);

        historico.setText("historic");

        listaautores.setText("list actor");
        listaautores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaautoresActionPerformed(evt);
            }
        });
        historico.add(listaautores);

        listaclientes.setText("list client");
        listaclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaclientesActionPerformed(evt);
            }
        });
        historico.add(listaclientes);

        jMenuBar1.add(historico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarlivroActionPerformed
        RegistrarLivro registrarolivro = new RegistrarLivro(this,true);
        registrarolivro.setVisible(true);
    }//GEN-LAST:event_registrarlivroActionPerformed

    private void registrarautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarautorActionPerformed
        RegistrarAutor registraroautor = new RegistrarAutor(this,true);
        registraroautor.setVisible(true);
    }//GEN-LAST:event_registrarautorActionPerformed

    private void registrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarclienteActionPerformed
        RegistrarCliente registrarolivro = new RegistrarCliente(this,true);
        registrarolivro.setVisible(true);
    }//GEN-LAST:event_registrarclienteActionPerformed

    private void livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosActionPerformed
        Loja mostrarlivros = new Loja(this, true);
        mostrarlivros.setVisible(true);
    }//GEN-LAST:event_livrosActionPerformed

    private void listaautoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaautoresActionPerformed
        ListaAutores historicodcompra = new ListaAutores(this, true);
        historicodcompra.setVisible(true);
    }//GEN-LAST:event_listaautoresActionPerformed

    private void listaclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaclientesActionPerformed
        ListaClientes historicodemprestimo = new ListaClientes(this, true);
        historicodemprestimo.setVisible(true);
    }//GEN-LAST:event_listaclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu historico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaautores;
    private javax.swing.JMenuItem listaclientes;
    private javax.swing.JMenuItem livros;
    private javax.swing.JMenu loja;
    private javax.swing.JMenu registrar;
    private javax.swing.JMenuItem registrarautor;
    private javax.swing.JMenuItem registrarcliente;
    private javax.swing.JMenuItem registrarlivro;
    // End of variables declaration//GEN-END:variables
}
